package com.yps.autogenerated;


import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;

import com.yps.base.AutoConnecter;
import com.yps.base.music.IMusicManager;
import com.yps.base.music.IPlayListener;
import com.yps.base.version.IVersionControl;
import com.yps.base.version.IVersionInfoListener;
import com.yps.base.voice.IVoiceManager;
import com.yps.base.voice.IVoiceProcess;


public class MainActivity extends Activity {
    private static final String TAG = "MainActivity";
    private IMusicManager iIMusicManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
//        bindService22();
    }


    private void bindIVersionControlService22() {
        new AutoConnecter<>(IVersionControl.class, this).connect(iVersionControl -> {
            iVersionControl.checkUpdate(new IVersionInfoListener() {
                @Override
                public void onNewVersion(String vName, int vCode) {
                    int versionCode = iVersionControl.getVersionCode();
                    Log.d(TAG, "onNewVersion: " + vName + "---" + vCode);
                }

                @Override
                public void onLastVersion() {
                    Log.d(TAG, "onLastVersion: ");

                }
            });
        });
    }

    private void bindIMusicManagerService() {
        new AutoConnecter<>(IMusicManager.class, this).connect(iIMusicManager -> {
            this.iIMusicManager = iIMusicManager;
            iIMusicManager.addPlayListener(new IPlayListener() {
                @Override
                public void onPlayStatus(int status) {
                    Log.d(TAG, "onPlayStatus: " + status);
                }
            });
        });
    }

    public void Connect(View view) {
        bindIVersionControlService22();
        bindIMusicManagerService();
    }

    public void Action2(View view) {
        iIMusicManager.pause(111);
    }

    public void Action1(View view) {
        iIMusicManager.play(555111);
    }
}